[project]
name = "labyrinth-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "contextily>=1.6.2",
    "geopandas>=1.0.1",
    "matplotlib>=3.10.1",
    "pygame>=2.6.1",
    "shapely>=2.1.0",
    "tqdm>=4.67.1",
]
